source 'https://rubygems.org'

ruby '3.3.5'

# Middleman Gems
gem 'middleman'
gem 'middleman-livereload'
gem 'middleman-aria_current'
gem 'middleman-autoprefixer'
gem 'middleman-inline_svg'
gem 'middleman-minify-html'
gem 'middleman-robots'

# Assets Pipeline Gems
gem 'builder', '~> 3.0'
gem 'bourbon'

# Build Pipeline Gems
gem 'htmlcompressor'
gem 'yui-compressor'
gem 'terser', '~> 1.1'

# Fix Middleman Issu
gem 'haml', '>= 4.0.5', '< 6.0'

# Windows Support
gem 'wdm' if Gem.win_platform?
