source 'https://rubygems.org'

gem 'middleman', git: 'https://github.com/ntkme/middleman', branch: sass-embedded'
gem "middleman-sprockets", '~> 4.0.0'
gem 'middleman-livereload'
gem 'middleman-autoprefixer'
gem 'middleman-inline_svg'
gem 'middleman-minify-html'

# Asset Pipeline Gems
gem 'sprockets', '~> 3.7.2'
gem 'builder'
gem 'bourbon'
# gem 'sass', '~> 3.7.4'

# Build Pipeline Gems
gem 'htmlcompressor'
gem 'yui-compressor'
gem 'terser', '~> 1.1'

# Windows Support
gem 'wdm' if Gem.win_platform?
