source 'https://www.rubygems.org'
ruby file: '.ruby-version'

# Bourbon
gem 'bourbon'
gem 'builder'

# Core
gem 'middleman'
gem 'middleman-livereload'
gem 'middleman-autoprefixer'
gem 'middleman-inline_svg'
gem 'middleman-minify-html'
gem 'middleman-pagegroups'
gem 'middleman-robots'
gem 'middleman-search_engine_sitemap'
gem 'middleman-sitemap-ping'

# Build Pipeline Gems
gem 'htmlcompressor'
gem 'yui-compressor'
gem 'nokogiri'
gem 'terser'

# Windows Support
gem 'wdm' if Gem.win_platform?
